---
vm_guest_id: centos7_64Guest

# VM Hardware
vm_hardware_memory_gb: 2
vm_hardware_cpu: 1
vm_hardware_controller: paravirtual

# VM Disk
vm_disk_size: 20
vm_disk_type: thin
vm_disk_datastore: vsanDatastore

# VM Network
vm_network_label: Management
vm_network_type: vmxnet3
